<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<title>FastSearch LBC</title>
	</head>
	<body>
		<header class="text-center">
			<div class="container">
				<h1>
					Fastsearch
				</h1>
				<p>
					Un puissant moteur de recherche pour les annonces <a href="https://www.leboncoin.fr">LeBonCoin</a>.
				</p>
			</div>
		</header>
		<div class="container">
			<form action="/search" method="POST">
				<div class="form-group">
					<label for="objectNameLabel">Recherche</label>
					<input type="text" class="form-control" id="searchRequest" placeholder="Que recherchez vous ?">
				</div>
				<div class="form-group">
					<label for="objectInTitleLabel">Termes exacts ?</label>
					<input type="checkbox" class="form-check" id="searchInTitle">
				</div>
				<div class="form-group">
					<label for="objectInTitleLabel">Rechercher uniquement dans le titre ?</label>
					<input type="checkbox" class="form-check" id="searchInTitle" checked>
				</div>
				<div class="form-group">
					<label for="objectNameLabel">Ne pas inclure</label>
					<input type="text" class="form-control" id="searchNotInclude" placeholder="Exemple: ECC">
				</div>
				<div>
					<button type="submit" class="btn btn-primary">Envoyer</button>
				</div>
			</form>
		</div>
		<footer class="text-center">
			<hr>
			<div>
				<p>
					Made with love by <span>tiboitel</span> @ 2018.
				</p>
			</div>
		</footer>
	</body>
</html>
